[2023-03-23T10:21:08.398+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.biqquery_external_table scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T10:21:08.405+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.biqquery_external_table scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T10:21:08.405+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T10:21:08.405+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-23T10:21:08.405+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T10:21:08.415+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryCreateExternalTableOperator): biqquery_external_table> on 2023-03-22 00:00:00+00:00
[2023-03-23T10:21:08.419+0000] {standard_task_runner.py:55} INFO - Started process 270 to run task
[2023-03-23T10:21:08.421+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'biqquery_external_table', 'scheduled__2023-03-22T00:00:00+00:00', '--job-id', '1935', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_script_gcp.py', '--cfg-path', '/tmp/tmpexer3xp8']
[2023-03-23T10:21:08.422+0000] {standard_task_runner.py:83} INFO - Job 1935: Subtask biqquery_external_table
[2023-03-23T10:21:08.431+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-23T10:21:08.445+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-03-23T10:21:08.469+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.biqquery_external_table scheduled__2023-03-22T00:00:00+00:00 [running]> on host 4b3eeaf199d3
[2023-03-23T10:21:08.522+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=biqquery_external_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T00:00:00+00:00
[2023-03-23T10:21:08.522+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-03-23T10:21:08.523+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-23T10:21:09.334+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=biqquery_external_table, execution_date=20230322T000000, start_date=20230323T102108, end_date=20230323T102109
[2023-03-23T10:21:09.357+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-23T10:21:09.373+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
